#!/usr/bin/python2.7
import sys; sys.path.insert(0, '.pylib')
import time
from datetime import datetime
from hosted import config, node, log
from hosted.scheduler import verified_timezone, utc_to_local

config.restart_on_update()

tz = verified_timezone(
    config.metadata['timezone'] if config.timezone == "device" else config.timezone
)

while time.time() < 100000:
    time.sleep(1)

while 1:
    now = utc_to_local(datetime.utcnow(), tz).replace(microsecond=0)
    is_day = config.schedule.active(tz, now)
    log('now is %s: day: %s' % (now, is_day), name='scheduler')
    node["/is_day"]("true" if is_day else "false")
    time.sleep(5)
